language: node_js
dist: trusty
node_js:
  - "10"
install:
  - npm i
  - git clone https://github.com/SukkaW/CheckSSL.git --depth=2
script:
  - npm run build
  - cd CheckSSL
  - chmod +x checker.sh
  - ./checker.sh suka.moe www.suka.moe blog.suka.moe lab.suka.moe cdn.suka.moe theme.suka.moe suka.js.org
  - cp -rf ./output/ct.json ../public/ct.json
branches:
  only:
    - master
cache:
  directories:
    - node_modules
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  target_branch: gh-pages
  email: $GITHUB_EMAIL
  name: $GITHUB_USER
  local-dir: public
  on:
    branch: master
