language: node_js
dist: trusty
node_js:
  - "10"
install:
  - npm i
  - git clone https://github.com/ChenYFan/CheckSSL --depth=2
script:
  - npm run build
  - cd CheckSSL
  - chmod +x checker.sh
  - ./checker.sh www.utermux.dev blog.utermux.dev github.fastgithub.tk status.utermux.dev ssl.utermux.dev pan.utermux.dev 
  - cp -rf ./output/ct.json ../public/ct.json
  - echo "ssl.utermux.dev" > ../public/CNAME
branches:
  only:
    - master
cache:
  directories:
    - node_modules
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  target_branch: gh-pages
  email: $GITHUB_EMAIL
  name: $GITHUB_USER
  local-dir: public
  on:
    branch: master
