name: SSL Check

on: 
  push:
    branches: 
      - master
  schedule:
    - cron: '0 16 * * *' 

jobs:
  CheckSSL:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '10'
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Install & Build
      run: |
        TZ='Asia/Shanghai'; export TZ
        npm i
        git clone https://github.com/yfun-lab/CheckSSL --depth=2
        npm run build
        cd CheckSSL
        chmod +x checker.sh
        ./checker.sh 2096779623.github.io test686.cf vip.test686.cf m3u8.test686.cf dino.test686.cf down.test686.cf test686.eu.org unlock.test686.cf liferestart.test686.cf www.test686.cf 
        cp -rf ./output/ct.json ../public/ct.json
        echo "ssl.test686.eu.org" > ../public/CNAME
        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_dir: ./public
